import { collection, addDoc, getDocs, query, where, orderBy, updateDoc, doc, setDoc, getDoc, serverTimestamp, type FieldValue } from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { db, storage } from './firebase';
import type { HazardAnalysis, CleanupAnalysis } from './gemini';
import { SQUAD_MEMBERS } from './dummyData';
import type { UserStats } from '../components/squads/UserProfileModal';

export interface ParkProfile {
  id: string; // Google Place ID
  name: string;
  integrity: number; // 0-100 score
  location: { lat: number; lng: number };
  isCustom?: boolean;
  createdAt?: FieldValue | Date;
  amenities?: ParkAmenity[];
  photoUrl?: string;
}

export interface ParkAmenity {
  label: string;
  icon: string;
  confirmedBy: string[]; // User IDs
}

export interface HazardReport extends HazardAnalysis {
  id?: string;
  parkId: string;
  photoUrl: string;
  createdAt: FieldValue | Date;
  status: 'Open' | 'Resolved';
}

export interface CleanupReport extends CleanupAnalysis {
  id?: string;
  parkId: string;
  photoUrl: string;
  type: string;
  createdAt: FieldValue | Date;
}

export interface Rally {
  id?: string;
  parkId: string;
  parkName: string;
  title: string;
  description: string;
  date: Date | string; // Ideally a Timestamp but simplifying for MVP
  organizer: string; // User ID or Name
  attendees: string[]; // List of User IDs/Names
  hazardId?: string; // Optional link to a specific reported hazard
  smartEquipmentManifest?: string[]; // Tools to bring, generated by AI
  createdAt: FieldValue | Date;
}

export type ParkActivityItem = 
  | (HazardReport & { activityType: 'hazard' })
  | (CleanupReport & { activityType: 'cleanup' })
  | (Rally & { activityType: 'rally' });

/**
 * Uploads a photo to Firebase Storage and returns the public URL.
 */
export async function uploadEvidence(file: File, parkId: string): Promise<string> {
  const timestamp = Date.now();
  const storageRef = ref(storage, `evidence/${parkId}/${timestamp}_${file.name}`);
  
  const snapshot = await uploadBytes(storageRef, file);
  const downloadUrl = await getDownloadURL(snapshot.ref);
  return downloadUrl;
}

/**
 * Submits a new Hazard Report to Firestore and updates the park's integrity score.
 */
export async function submitHazardReport(
  parkId: string, 
  parkName: string, 
  location: { lat: number; lng: number }, 
  file: File, 
  analysis: HazardAnalysis
): Promise<HazardReport> {
  // 1. Upload photo
  const photoUrl = await uploadEvidence(file, parkId);

  // 2. Prepare report document
  const reportData = {
    ...analysis,
    parkId,
    photoUrl,
    status: 'Open',
    createdAt: serverTimestamp()
  };

  // 3. Save to "hazards" collection
  const hazardsRef = collection(db, 'hazards');
  const docRef = await addDoc(hazardsRef, reportData);

  // 4. Update the park's integrity score based on the severity
  await decreaseParkIntegrity(parkId, parkName, location, analysis.severity);

  return { ...reportData, id: docRef.id } as HazardReport;
}

/**
 * Decreases a park's integrity score based on the severity of a reported hazard.
 * If the park doesn't exist in our DB yet, it creates it starting at 100 before the deduction.
 */
async function decreaseParkIntegrity(
  parkId: string, 
  parkName: string, 
  location: { lat: number; lng: number }, 
  severity: string
) {
  const parkRef = doc(db, 'parks', parkId);
  const parkSnap = await getDoc(parkRef);

  let currentIntegrity = 100;

  if (!parkSnap.exists()) {
    // Create new park baseline if it doesn't exist
    await setDoc(parkRef, {
      id: parkId,
      name: parkName,
      location,
      integrity: 100
    });
  } else {
    currentIntegrity = parkSnap.data().integrity;
  }

  // Deduct points based on severity
  let penalty = 0;
  if (severity === 'Attention Needed') penalty = 5;
  if (severity === 'Tools Required') penalty = 15;
  if (severity === 'Hazardous/Biohazard') penalty = 30;

  const newIntegrity = Math.max(0, currentIntegrity - penalty);

  await updateDoc(parkRef, {
    integrity: newIntegrity
  });
}

/**
 * Gets all active hazard reports for a specific park.
 */
export async function getParkHazards(parkId: string): Promise<HazardReport[]> {
  const hazardsRef = collection(db, 'hazards');
  const q = query(
    hazardsRef, 
    where('parkId', '==', parkId),
    where('status', '==', 'Open'),
    orderBy('createdAt', 'desc')
  );

  const querySnapshot = await getDocs(q);
  return querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as HazardReport));
}

/**
 * Gets a combined reverse-chronological activity feed (hazards & cleanups) for a specific park.
 */
export async function getParkActivity(parkId: string): Promise<ParkActivityItem[]> {
  const hazardsRef = collection(db, 'hazards');
  const cleanupsRef = collection(db, 'cleanups');
  const ralliesRef = collection(db, 'rallies');

  const qHazards = query(hazardsRef, where('parkId', '==', parkId), orderBy('createdAt', 'desc'));
  const qCleanups = query(cleanupsRef, where('parkId', '==', parkId), orderBy('createdAt', 'desc'));
  const qRallies = query(ralliesRef, where('parkId', '==', parkId), orderBy('createdAt', 'desc'));

  const [hazardsSnap, cleanupsSnap, ralliesSnap] = await Promise.all([
    getDocs(qHazards), 
    getDocs(qCleanups),
    getDocs(qRallies)
  ]);

  const activities: ParkActivityItem[] = [
    ...hazardsSnap.docs.map(d => ({ ...(d.data() as HazardReport), id: d.id, activityType: 'hazard' as const })),
    ...cleanupsSnap.docs.map(d => ({ ...(d.data() as CleanupReport), id: d.id, activityType: 'cleanup' as const })),
    ...ralliesSnap.docs.map(d => ({ ...(d.data() as Rally), id: d.id, activityType: 'rally' as const }))
  ];

  // Sort descending by timestamp
  activities.sort((a, b) => {
    const aTime = (a.createdAt as { toMillis?: () => number })?.toMillis?.() 
      || (a.createdAt instanceof Date ? a.createdAt.getTime() : Date.now());
    const bTime = (b.createdAt as { toMillis?: () => number })?.toMillis?.() 
      || (b.createdAt instanceof Date ? b.createdAt.getTime() : Date.now());
    return bTime - aTime;
  });

  return activities;
}

/**
 * Gets the profile (including dynamic integrity score) for a specific park.
 */
export async function getParkProfile(parkId: string): Promise<ParkProfile | null> {
  const parkRef = doc(db, 'parks', parkId);
  const parkSnap = await getDoc(parkRef);

  if (parkSnap.exists()) {
    return parkSnap.data() as ParkProfile;
  }
  return null;
}

/**
 * Adds a user-reported custom park to the database.
 */
export async function addCustomPark(name: string, location: { lat: number; lng: number }): Promise<ParkProfile> {
  const parksRef = collection(db, 'parks');
  const docRef = await addDoc(parksRef, {
    name,
    location,
    integrity: 100,
    isCustom: true,
    createdAt: serverTimestamp()
  });

  // The ID is generated by Firestore, so we update the doc to include its own ID for easier querying later
  await updateDoc(docRef, { id: docRef.id });

  return { id: docRef.id, name, location, integrity: 100 };
}

/**
 * Retrieves all user-reported custom parks from the database.
 */
export async function getCustomParks(): Promise<ParkProfile[]> {
  const parksRef = collection(db, 'parks');
  const q = query(parksRef, where('isCustom', '==', true));
  const snapshot = await getDocs(q);
  
  return snapshot.docs.map(doc => doc.data() as ParkProfile);
}

/**
 * Retrieves ALL parks that have a record in the database (custom or standard).
 * Useful for building a heatmap of civic activity.
 */
export async function getAllRegisteredParks(): Promise<ParkProfile[]> {
  const parksRef = collection(db, 'parks');
  const snapshot = await getDocs(parksRef);
  
  return snapshot.docs.map(doc => doc.data() as ParkProfile);
}

/**
 * Submits a Cleanup Verification Report to Firestore and updates the park's integrity score.
 */
export async function submitCleanupVerification(
  parkId: string, 
  parkName: string,
  location: { lat: number; lng: number },
  file: File, 
  analysis: CleanupAnalysis
): Promise<CleanupReport> {
  // 1. Upload photo
  const photoUrl = await uploadEvidence(file, parkId);

  // 2. Prepare report document
  const reportData = {
    ...analysis,
    parkId,
    photoUrl,
    type: 'Cleanup',
    createdAt: serverTimestamp()
  };

  // 3. Save to "cleanups" collection
  const cleanupsRef = collection(db, 'cleanups');
  const docRef = await addDoc(cleanupsRef, reportData);

  // 4. Update the park's integrity score if AI confirms it is clean
  if (analysis.isClean) {
     await increaseParkIntegrity(parkId, parkName, location);
  }

  return { ...reportData, id: docRef.id };
}

/**
 * Increases a park's integrity score (e.g. after a cleanup).
 * Caps at 100.
 */
async function increaseParkIntegrity(
  parkId: string, 
  parkName: string, 
  location: { lat: number; lng: number }
) {
  const parkRef = doc(db, 'parks', parkId);
  const parkSnap = await getDoc(parkRef);

  let currentIntegrity = 100;

  if (!parkSnap.exists()) {
    await setDoc(parkRef, {
      id: parkId,
      name: parkName,
      location,
      integrity: 100
    });
  } else {
    currentIntegrity = parkSnap.data().integrity;
  }

  // Restore points for a verified cleanup
  const newIntegrity = Math.min(100, currentIntegrity + 15);

  await updateDoc(parkRef, {
    integrity: newIntegrity
  });
}

/**
 * Creates a new Rally (community cleanup event)
 */
export async function createRally(
  parkId: string,
  parkName: string,
  title: string,
  description: string,
  date: Date,
  organizer: string,
  hazardId?: string,
  smartEquipmentManifest?: string[]
): Promise<Rally> {
  const ralliesRef = collection(db, 'rallies');
  
  const rallyData = {
    parkId,
    parkName,
    title,
    description,
    date: date.toISOString(),
    organizer,
    attendees: [organizer], // Organizer is automatically an attendee
    hazardId: hazardId || null,
    smartEquipmentManifest: smartEquipmentManifest || [],
    createdAt: serverTimestamp()
  };

  const docRef = await addDoc(ralliesRef, rallyData);
  return { ...rallyData, id: docRef.id } as unknown as Rally;
}

/**
 * Allows a user to RSVP to a rally
 */
export async function joinRally(rallyId: string, userName: string): Promise<void> {
  const rallyRef = doc(db, 'rallies', rallyId);
  const rallySnap = await getDoc(rallyRef);

  if (!rallySnap.exists()) {
    throw new Error("Rally not found");
  }

  const data = rallySnap.data();
  const attendees = data.attendees || [];
  
  if (!attendees.includes(userName)) {
    await updateDoc(rallyRef, {
      attendees: [...attendees, userName]
    });
  }
}

/**
 * Retrieves all users from the database.
 * Auto-seeds the database with dummy data if the users collection is entirely empty.
 */
export async function getUsers(): Promise<UserStats[]> {
  const usersRef = collection(db, 'users');
  const snapshot = await getDocs(usersRef);

  // If we have users, return them
  if (!snapshot.empty) {
    // Sort so Captain is first based on dummy data logic, or by territoryRank
    const users = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as UserStats & { id: string }));
    return users.sort((a, b) => a.territoryRank - b.territoryRank);
  }

  // Auto-seed if the collection is empty
  console.log("No users found in Firestore. Auto-seeding 'users' collection with dummy data...");
  const seededUsers: (UserStats & { id: string })[] = [];
  
  for (const member of SQUAD_MEMBERS) {
     const docRef = await addDoc(usersRef, {
        ...member,
        createdAt: serverTimestamp()
     });
     // Optional: If you want the document ID stamped onto the user record
     await updateDoc(docRef, { id: docRef.id });
     seededUsers.push({ ...member, id: docRef.id });
  }

  return seededUsers.sort((a, b) => a.territoryRank - b.territoryRank);
}

/**
 * Updates a user's last checked-in location.
 */
export async function checkInToPark(
  userId: string,
  parkId: string,
  parkName: string,
  lat: number,
  lng: number
): Promise<void> {
  const userRef = doc(db, 'users', userId);
  await updateDoc(userRef, {
    lastCheckIn: {
      parkId,
      parkName,
      lat,
      lng,
      timestamp: serverTimestamp()
    }
  });
}

/**
 * Confirms or unconfirms an amenity for a park.
 */
export async function confirmParkAmenity(
  parkId: string,
  amenityLabel: string,
  userId: string
): Promise<void> {
  const parkRef = doc(db, 'parks', parkId);
  const parkSnap = await getDoc(parkRef);
  
  if (!parkSnap.exists()) {
    await setDoc(parkRef, {
      id: parkId,
      name: "Community Park",
      location: { lat: 0, lng: 0 },
      integrity: 100,
      amenities: []
    });
  }
  
  const snap = !parkSnap.exists() ? await getDoc(parkRef) : parkSnap;
  const data = snap.data();
  const amenities: ParkAmenity[] = data?.amenities || [];
  
  const updatedAmenities = amenities.map(amenity => {
    if (amenity.label === amenityLabel) {
      const confirmedBy = [...(amenity.confirmedBy || [])];
      const index = confirmedBy.indexOf(userId);
      if (index > -1) {
        confirmedBy.splice(index, 1); // Remove
      } else {
        confirmedBy.push(userId); // Add
      }
      return { ...amenity, confirmedBy };
    }
    return amenity;
  });
  
  await updateDoc(parkRef, { amenities: updatedAmenities });
}

/**
 * Adds a new suggested amenity to a park.
 */
export async function addParkAmenity(
  parkId: string,
  label: string,
  icon: string,
  userId: string // First confirmer
): Promise<void> {
  const parkRef = doc(db, 'parks', parkId);
  const parkSnap = await getDoc(parkRef);
  
  if (!parkSnap.exists()) {
    await setDoc(parkRef, {
      id: parkId,
      name: "Community Park",
      location: { lat: 0, lng: 0 },
      integrity: 100,
      amenities: []
    });
  }
  
  const snap = !parkSnap.exists() ? await getDoc(parkRef) : parkSnap;
  const data = snap.data();
  const amenities: ParkAmenity[] = data?.amenities || [];
  
  // Check if it already exists
  if (amenities.some(a => a.label.toLowerCase() === label.toLowerCase())) {
    return;
  }
  
  const newAmenity: ParkAmenity = {
    label,
    icon,
    confirmedBy: [userId]
  };
  
  await updateDoc(parkRef, {
    amenities: [...amenities, newAmenity]
  });
}
